### ISSUE TITLE
SQL EXPRESS!!!

### ISSUE THREAD

**Issue by gburns53** [marcomilon/ezphp#11]
How do we get this to work with SQL Express? I put the Driver DLL's in the EXT folder with no success. I get 'could not find driver'. 

It would be a real nice add to package this with SQL Server drivers and just have them install it separate and tell us how to make sure it works. Thanks! This rules otherwise. It's so light-weight its preposterous.

**Comment by marcomilon** [comment]
I'm sorry this is more an issue of PHP in windows than EzPHP.

I think you should do research on how to activate a module in PHP. 
Probably by editing php.ini
