### ISSUE TITLE
Logo for ezphp

### ISSUE THREAD

**Issue by marcomilon** [marcomilon/ezphp#12]
Hello, 

If you like ezphp and have design skills, it will be great if you purpose a logo for the App.

Thanksss

**Comment by mirzazulfan** [comment]
Hello @marcomilon what do you think about this? 
![ezphp](https://user-images.githubusercontent.com/36124339/60332096-4a402880-99c0-11e9-971b-0e1e00c4c15f.png)

**Comment by marcomilon** [comment]
Hello, i like it. 
Thank you very much

**Comment by mirzazulfan** [comment]
I'm glad you liked it. What color do you prefer? I'll send all files and create a pr. Regard!

**Comment by marcomilon** [comment]
I like the purple version

**Comment by mirzazulfan** [comment]
Hi @marcomilon I've created a pr #14 and you can also download all files on [Google Drive](https://drive.google.com/drive/folders/1cFC37EWkgfU70Yd2BJ29pCpRyYPOEEtf)

**Comment by marcomilon** [comment]
Thanks, i will merge i soon

**Comment by itgraf** [comment]
Благодарю


>Среда, 10 июля 2019, 23:56 +03:00 от Marco Milon <notifications@github.com>:
>
>Closed  #12 .
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением Акланов Р.Р.
тел.89648601201 
e-mail :  koraooo@me.com
